name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: want to see included
      id: want-to-see-included
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: want to see included
        setup-command: ''
        command: "./input_test.py"
        input: '1'
        expected-output: '0'
        comparison-method: contains
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        WANT-TO-SEE-INCLUDED_RESULTS: "${{steps.want-to-see-included.outputs.result}}"
      with:
        runners: want-to-see-included
