name: Cloning Repo
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Clone Repo
      uses: Coachbot-Swarm-System/clone-github-repo-action@v2
      with:
        depth: 1
        branch: 'main'
        owner: 'dornadulavaishnavi'
        repository: 'Coachbot-Swarm-System/coachbot-swarm-system-submission-dornadulavaishnavi'