name: Testing Input Validity
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Clone Repo
      uses: actions/clone-github-repo-action@v2
        with:
          depth: 1
          branch: 'main'