name: Copying Required Files
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Testing validity
      id: testing-validity
      uses: education/autograding-io-grader@v1
      with:
        test-name: Testing validity
        command: python ./get_files.py
        input: '0'
        expected-output: 'Copied'
        comparison-method: contains
        timeout: 2
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        TESTING-VALIDITY_RESULTS: "${{steps.testing-validity.outputs.result}}"
      with:
        runners: testing-validity
