name: Test
defaults:
  run:
    shell: bash
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dependancies
      run: |
        python -m pip install --upgrade pip
        pip install numpy
        pip install py_compile
    - name: Check validity
      run: python ./input_validity_test_main.py